### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jimmythompson** [srobo/brand#5]
Hey @PeterJCLaw. I forgot to add a license before merging your pull request.

Before this gets out of hand, do you mind your changes being licensed under MIT?

**Comment by PeterJCLaw** [comment]
I'm fine with MIT in principle, though as this is our _brand_ I'm not sure we want to allow others to use it?

Or do you feel that protections on our logo are sufficient to prevent imitations?

Related question (though this maybe isn't the right place to ask): do we have a trademark on the logo?

**Comment by jimmythompson** [comment]
Regarding the copyright of the logo, I "made" the logo and transferred copyright to Student Robotics. There's probably some legal vagueness about the logo being represented as code (i.e. SVG) which needs to be cleared up.

We haven't yet applied for a trademark, I am looking into it.

I think the benefits of allowing contributors and re-use outweigh the cost of licensing this repository. As far as I know, nobody has really tried to impersonate us, but our brand is inconsistent. 😄

**Comment by PeterJCLaw** [comment]
ok, I'm happy with MIT here then.

I think we previously already had a trademark on the old logo, though I'm not sure.
